### PR TITLE
Add xstream implementation

### PR DESCRIPTION
**Pull request by mohamedhayibor**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Does it adhere to the ES Observable spec?

> Note that this list is focused on the JavaScript Observable proposal and Observables in general, **not Observable implementations not adhering to the proposed spec** or Observables in other languages.

## 

// @staltz

**Comment by sindresorhus** [comment]
@staltz

**Comment by staltz** [comment]
Not yet. When it does, I'll remember to send you a PR. Thanks.

This can be closed IMO.

**Comment by mohamedhayibor** [comment]
Thanks for the info @staltz

**Pull request closed without merging**
